products:
  dep-plugin:
    build:
      main-pkg: .
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
      version-var: github.com/palantir/godel-dep-plugin/cmd.Version
group-id: com.palantir.godel-dep-plugin
